name: slack-notification

on: [push, pull_request, issues]

jobs:
  slack-notification:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v1.1.0
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: test
          slack-text: A new *${{ github.event_name }}* is made in *${{ github.repository }}* 🎈
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"